### ISSUE TITLE
Progress Tracking.

### ISSUE THREAD

**Issue by J-P-S-O** [J-P-S-O/Http-Server#1]
- [x] - add more colors and descriptions and logging.
- [ ] - add notification for server crashing
- [ ] - creating log of dangerous requests
- [ ] - executing as background
- [ ] - adding as package to npm
- [ ] - global command `Web-Server`
- [ ] - Add typescript support
- [ ]  - fix the "Dir listing bug"

**Comment by J-P-S-O** [comment]
See #31
